const sb=supabase.createClient(SS_CONFIG.SUPABASE_URL,SS_CONFIG.SUPABASE_PUBLISHABLE_KEY),$=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function catalog(){let{data:ss}=await sb.from("sections").select("*").order("display_order"),{data:pp}=await sb.from("products").select("*").order("display_order");$("#catalog").innerHTML=ss?.length?ss.map(s=>`<section class="collection"><h3>${esc(s.name)}</h3><p>${esc(s.description)}</p><div class="grid">${(pp||[]).filter(p=>p.section_id===s.id).map(p=>`<a class="card" href="${esc(p.product_link)}" target="_blank" rel="noopener"><img src="${esc(p.image_url)}"><div><h4>${esc(p.name)}</h4><p>${esc(p.description)}</p><span>View Product →</span></div></a>`).join("")}</div></section>`).join(""):"No collections yet."}
async function route(){let a=location.hash==="#admin";$("#site").classList.toggle("hide",a);$("#admin").classList.toggle("hide",!a);if(a)auth();else catalog()}
async function auth(){let{data:{session}}=await sb.auth.getSession();$("#login").classList.toggle("hide",!!session);$("#dash").classList.toggle("hide",!session);if(session)load()}
$("#loginForm").onsubmit=async e=>{e.preventDefault();let{error}=await sb.auth.signInWithPassword({email:$("#email").value,password:$("#password").value});$("#loginMsg").textContent=error?.message||"";auth()}
$("#logout").onclick=async()=>{await sb.auth.signOut();auth()}
async function load(){let{data:ss}=await sb.from("sections").select("*").order("display_order"),{data:pp}=await sb.from("products").select("*").order("display_order");window.ss=ss||[];window.pp=pp||[];$("#psection").innerHTML='<option value="">Choose section</option>'+window.ss.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("");$("#sections").innerHTML=window.ss.map(s=>`<div class="row"><b>${esc(s.name)}</b><button class="danger" onclick="delSection(${s.id})">Delete</button></div>`).join("");$("#products").innerHTML=window.pp.map(p=>`<div class="productrow"><img src="${esc(p.image_url)}"><div class="grow"><b>${esc(p.name)}</b></div><button class="danger" onclick="delProduct(${p.id})">Delete</button></div>`).join("")}
$("#sectionForm").onsubmit=async e=>{e.preventDefault();let{error}=await sb.from("sections").insert({name:$("#sname").value,description:$("#sdesc").value||null,display_order:+$("#sorder").value||0});msg(error?.message||"Section added");if(!error){e.target.reset();load()}}
$("#productForm").onsubmit=async e=>{e.preventDefault();msg("Uploading…");let f=$("#pimage").files[0],path=`${Date.now()}-${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`,u=await sb.storage.from(SS_CONFIG.STORAGE_BUCKET).upload(path,f);if(u.error)return msg(u.error.message);let{data:d}=sb.storage.from(SS_CONFIG.STORAGE_BUCKET).getPublicUrl(path),{error}=await sb.from("products").insert({section_id:+$("#psection").value,name:$("#pname").value,description:$("#pdesc").value||null,product_link:$("#plink").value,image_url:d.publicUrl,display_order:+$("#porder").value||0});msg(error?.message||"Product added");if(!error){e.target.reset();load()}}
async function delSection(id){if(confirm("Delete section and its products?")){let{error}=await sb.from("sections").delete().eq("id",id);msg(error?.message||"Deleted");load()}}
async function delProduct(id){if(confirm("Delete product?")){let{error}=await sb.from("products").delete().eq("id",id);msg(error?.message||"Deleted");load()}}
function msg(x){$("#msg").textContent=x}addEventListener("hashchange",route);route();